# Generated by Django 4.2.4 on 2023-12-19 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('losts', models.TextField(blank=True, null=True)),
                ('brokens', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=12)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='roomreport',
            name='user',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='BookReport',
        ),
        migrations.DeleteModel(
            name='RoomReport',
        ),
    ]
