# Generated by Django 4.2.6 on 2023-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_complaint_isread_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='username',
            field=models.CharField(default='Anonim', max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(default='Aninom', max_length=500),
        ),
    ]
