# Generated by Django 4.2.6 on 2023-12-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0008_delete_roomreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
