# Generated by Django 4.2.6 on 2023-10-24 06:03

from django.db import migrations
from django.core.management import call_command



class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
    ]
