# Generated by Django 4.2.6 on 2023-10-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231024_1303'),
        ('book', '0004_auto_20231027_0201'),
    ]

    operations = [
    ]
